### ISSUE TITLE
Throws `IllegalStateException`

### ISSUE THREAD

**Issue by risu729** [risu729/erutcurts#25]
Threw `IllegalStateException` on pack auto-generation.

```
java.lang.IllegalArgumentException
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:131)
at io.github.risu729.erutcurts.structure.nbt.Block.<init>(Block.java:64)
at io.github.risu729.erutcurts.structure.nbt.Block.<init>(Block.java:53)
at io.github.risu729.erutcurts.structure.nbt.Structure.lambda$fromNbt$5(Structure.java:124)
at java.base/java.util.Optional.map(Optional.java:260)
at io.github.risu729.erutcurts.structure.nbt.Structure.lambda$fromNbt$6(Structure.java:106)
at com.google.common.collect.Streams$2.tryAdvance(Streams.java:446)
at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
at io.github.risu729.erutcurts.structure.nbt.Structure.fromNbt(Structure.java:126)
at io.github.risu729.erutcurts.structure.nbt.Structure.fromNbt(Structure.java:53)
at io.github.risu729.erutcurts.structure.behavior.Behavior.<init>(Behavior.java:81)
at io.github.risu729.erutcurts.structure.behavior.Behavior.generate(Behavior.java:138)
at io.github.risu729.erutcurts.structure.behavior.Behavior.generate(Behavior.java:128)
at io.github.risu729.erutcurts.structure.TargetType.convert(TargetType.java:95)
at io.github.risu729.erutcurts.structure.StructureListener.onMessageReceived(StructureListener.java:63)
at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:426)
at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:181)
at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:136)
at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:983)
at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:869)
at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:847)
at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1022)
at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by risu729** [comment]
The problem was: `tick_delay` was expected to be a positive integer, but it was 0.
